spring:
  application:
    name: developer
eureka:
  client:
    initial-instance-info-replication-interval-seconds: 2
    registry-fetch-interval-seconds: 30
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 30
ribbon:
  ServerListRefreshInterval:1000
